auto: true
include: [.htaccess]
exclude: [
  Rakefile,
  Gemfile,
  README.md,
  *.sublime-*
  ]
markdown: pandoc
pandoc:
  extensions:
    - blank_before_header
    - fenced_code_blocks
    - smart
    - strikeout
    - superscript
    - subscript
    - footnotes
    - inline_notes
    - definition_lists

name: 'm-andersen.net'
description: 'Fatherhood, geekery, fitness, social work'
url: http://m-andersen.net
author:
  name: 'Martin Andersen'
  email: 'draugen@draugrheim.net'

project_dir: projects

asset_pipeline:
  bundle: false            # Default = true
  compress: false          # Default = true
  output_path: assets     # Default = assets
  display_path: nil       # Default = nil
  gzip: false             # Default = false


flickr:
  api_key: 'e86e03c748a53887b237e691c55cf7d3'
  secret: '2ba99ec1778e2ca3'

flickr_set:
  gallery_tag:   'p'
  gallery_class: 'gallery'
  a_href:        nil
  a_target:      '_blank'
  image_rel:     ''
  image_size:    's'
  api_key:       'e86e03c748a53887b237e691c55cf7d3'

post:
  template: _templates/_post.txt
  extension: md
page:
  template: templates/_page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: jekyll-s3
  settings: nil
  source: _site/
  destination: nil